#!/bin/bash

set -e # fail on errors

rm -rd screenshots

adb root
adb wait-for-device

adb shell rm -f -rR /sdcard/Pictures/screenshots
adb shell rm -f -rR /sdcard/Pictures/error_screenshots

adb shell mkdir /sdcard/testdata
adb push testdata /sdcard/

adb emu gsm signal 4
adb shell cmd statusbar send-disable-flag clock notification-icons quick-settings statusbar-expansion

set +e # don't fail on errors

./gradlew :app:connectedDebugAndroidTest
exit_code=$?

adb pull /sdcard/Pictures/error_screenshots app/build
set -e # fail on errors
adb pull /sdcard/Pictures/screenshots

exit $exit_code
