#!/bin/bash

set -e # fail on errors

rm -rd screenshots

adb root
adb wait-for-device

adb shell rm -f -rR /sdcard/Pictures/screenshots
adb shell rm -f -rR /sdcard/Pictures/error_screenshots

adb shell mkdir /sdcard/testdata
adb push testdata /sdcard/

adb shell settings put global sysui_demo_allowed 1
sleep 1
adb shell am broadcast -a com.android.systemui.demo -e command enter

set +e # don't fail on errors

./gradlew :app:connectedDebugAndroidTest
exit_code=$?

adb shell am broadcast -a com.android.systemui.demo -e command exit
adb shell settings put global sysui_demo_allowed 0

adb pull /sdcard/Pictures/error_screenshots app/build
set -e # fail on errors
adb pull /sdcard/Pictures/screenshots

exit $exit_code
